### ISSUE TITLE
An overview of "sharp bits" of RxInfer

### ISSUE THREAD

**Issue by svilupp** [ReactiveBayes/RxInfer.jl#60]
This is inspired by [JAX Sharp Bits](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html) 

It would be awesome to have a documentation page describing the most unexpected differences to what a normal Julia user (or a Turing.jl user) would expect, eg,
- what the allowed operations are within a model (you cannot use functions // you cannot use sum on r a random variable array // you cannot use `+` with more than 2 arguments)
- what are the initialization needs and the minimum required
- troubleshooting frequently occurring problems
    - what should be in your function return statement (because you cannot just execute the model anyway. my guess: it's for the quantities that you want to manually subscribe to)
    - if your fit is bad at the very beginning of the time series, try increasing iterations
    - if you have BFE NaNs check that there isn't any input multiplied by a MvNormal with only zeros; if there is add, add `tiny` to the first column
    - if you get MethodError with q_ m_, try XYZ first

**Comment by bartvanerp** [comment]
Hi @SebastianCallh!

Our sincere apologies for the (extremely) late reply to your question. It just escaped our attention. Although your question seems a bit irrelated to the issue, I am happy to answer it here. From your description I get the feeling that you are looking for the following example in our docs: https://biaslab.github.io/RxInfer.jl/stable/examples/Kalman%20filter%20with%20LSTM%20network%20driven%20dynamic/#Generate-data. It basically describes a Kalman Filter whose transition matrices are modeled by a neural network (here powered by `Flux.jl`). The code is a bit rough there, because the neural network is trained simultaneously. If your network has already been trained, then you could make use of the more convenient `rxinference` function, which processes data sequentially in an online manner. Especially our `@autoupdates` macro might describe what you are looking for.

I hope this answers/solves your problem. If you would like to dive in a bit more detail regarding your implementation, feel free to open a separate issue in which we can discuss your implementation as we think this line of research is very interesting!

**Comment by SebastianCallh** [comment]
@bartvanerp Thank you so much for your polite response. I was a bit too eager when posting my question here, and completely agree it belongs in a separate issue. I will study the example you linked!

**Comment by bvdmitri** [comment]
@mhidalgoaraya

**Comment by albertpod** [comment]
Hi @mhidalgoaraya! I see this one has  "in progress" status. Are we working on it?

**Comment by albertpod** [comment]
ping @mhidalgoaraya

**Comment by mhidalgoaraya** [comment]
@albertpod, it is the first time that I see this. It seems that it was assigned to me. I can take care of it. Can we discuss it next week and you get me up to speed. Thanks
